GRANT CONNECT, TEMPORARY ON DATABASE datafuse TO GROUP cabinet_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES
    TO portal_admin WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, UPDATE, USAGE ON SEQUENCES
    TO portal_admin WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT EXECUTE ON FUNCTIONS
    TO portal_admin WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE ON TYPES
    TO portal_admin WITH GRANT OPTION;

-------------------------------------------------


ALTER DEFAULT PRIVILEGES 
    GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES
    TO portal_admin WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES 
    GRANT SELECT, UPDATE, USAGE ON SEQUENCES
    TO portal_admin WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES 
    GRANT EXECUTE ON FUNCTIONS
    TO portal_admin WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES 
    GRANT USAGE ON TYPES
    TO portal_admin WITH GRANT OPTION;

-------------------------------------------------
ALTER DEFAULT PRIVILEGES 
    GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES
    TO portal_admin WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES 
    GRANT SELECT, UPDATE, USAGE ON SEQUENCES
    TO portal_admin WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES 
    GRANT EXECUTE ON FUNCTIONS
    TO portal_admin WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES 
    GRANT USAGE ON TYPES
    TO portal_admin WITH GRANT OPTION;

--------------------------------------------------
GRANT ALL ON SCHEMA partman TO portal_admin WITH GRANT OPTION;
GRANT ALL ON SCHEMA backup TO portal_admin WITH GRANT OPTION;
GRANT ALL ON SCHEMA dblink TO portal_admin WITH GRANT OPTION;
GRANT ALL ON SCHEMA fias TO portal_admin WITH GRANT OPTION;
GRANT ALL ON SCHEMA jobmon TO portal_admin WITH GRANT OPTION;
GRANT ALL ON SCHEMA partman TO portal_admin WITH GRANT OPTION;
GRANT ALL ON SCHEMA portal TO portal_admin WITH GRANT OPTION;
GRANT ALL ON SCHEMA public TO portal_admin WITH GRANT OPTION;
GRANT ALL ON SCHEMA reports TO portal_admin WITH GRANT OPTION;
GRANT ALL ON SCHEMA slog TO portal_admin WITH GRANT OPTION;
GRANT ALL ON SCHEMA widgets TO portal_admin WITH GRANT OPTION;

REVOKE ALL ON DATABASE datafuse FROM public;
REVOKE ALL ON DATABASE datafuse FROM public;
