package ru.excbt.datafuse.nmk.report;

public enum ReportTypeKey {
	COMMERCE_REPORT, // CONS_REPORT,
	EVENT_REPORT, CONS_T1_REPORT, CONS_T2_REPORT, METROLOGICAL_REPORT, //
	CONSUMPTION_REPORT, CONSUMPTION_HISTORY_REPORT, CONSUMPTION_ETALON_REPORT, //
	LOG_JOURNAL_REPORT
}
